# Generated by Django 3.2.3 on 2021-08-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_app', '0002_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
